import { Router } from "express";

import userRoutes from "./users.routes.js";
import authenticationRoutes from "./authentication.routes.js";
import clienteRoutes from "./clientes.routes.js";
import servicioRoutes from "./servicios.routes.js";
import citaRoutes from "./citas.routes.js";
import citaServicioRoutes from "./citas_servicios.routes.js";
import proveedoresRoutes from "./proveedores.routes.js";
import productosRoutes from "./productos.routes.js";
import comprasRoutes from "./compras.routes.js";
import detallesComprasRoutes from "./detalles_compras.routes.js";
import ventasRoutes from "./ventas.routes.js";
import detallesVentasRoutes from "./detalles_ventas.routes.js";
import cobrosRoutes from "./cobros.routes.js";
import cuotasRoutes from "./cuotas.routes.js";
import sqlExecuteRoutes from "./sql_execute.routes.js";
import funcionariosRoutes from "./funcionarios.routes.js";
import notificacionesRoutes from "./notificaciones.routes.js";
import pagosRoutes from "./pagos.routes.js";
import valesRoutes from "./vales.routes.js";
import horaExtraRoutes from "./hora_extra.routes.js";
import planesRoutes from "./planes.routes.js";
import empresasRoutes from "./empresas.routes.js";
import deudasRoutes from "./deudas.routes.js";
import pdfGeneratorRoutes from "./pdf-generator.routes.js";
import utilsRoutes from "./utils.routes.js";
import cajaRoutes from "./cajas.routes.js";
import movimientosCajasRoutes from "./movimientos_cajas.routes.js";
import asistenciasRoutes from "./asistencias.routes.js";
// import fabricacionesRoutes from "./fabricaciones.routes.js";
// import detallesFabricacionesRoutes from "./detalle_fabricaciones.routes.js";
import tiposRoutes from "./tipos.routes.js";
// import tareaProductoRoutes from "./tarea_productos.routes.js";
import gastosRoutes from "./gastos.routes.js";
import presupuestosRoutes from "./presupuestos.routes.js";

const router = Router();

// Definir todas las rutas
router.use("/v1/api", userRoutes);
router.use("/v1/api/auth", authenticationRoutes);
router.use("/v1/api", citaRoutes);
router.use("/v1/api", citaServicioRoutes);
router.use("/v1/api", ventasRoutes);
router.use("/v1/api", valesRoutes);
router.use("/v1/api", sqlExecuteRoutes);
router.use("/v1/api", servicioRoutes);
router.use("/v1/api", proveedoresRoutes);
router.use("/v1/api", productosRoutes);
router.use("/v1/api", planesRoutes);
router.use("/v1/api", pagosRoutes);
router.use("/v1/api", notificacionesRoutes);
router.use("/v1/api", horaExtraRoutes);
router.use("/v1/api", funcionariosRoutes);
router.use("/v1/api", empresasRoutes);
router.use("/v1/api", detallesVentasRoutes);
router.use("/v1/api", detallesComprasRoutes);
router.use("/v1/api", cuotasRoutes);
router.use("/v1/api", comprasRoutes);
router.use("/v1/api", cobrosRoutes);
router.use("/v1/api", clienteRoutes);
router.use("/v1/api", deudasRoutes);
router.use("/v1/api", pdfGeneratorRoutes);
router.use("/v1/api", utilsRoutes);
router.use("/v1/api", cajaRoutes);
router.use("/v1/api", movimientosCajasRoutes);
router.use("/v1/api", asistenciasRoutes);
// router.use("/v1/api", fabricacionesRoutes);
// router.use("/v1/api", detallesFabricacionesRoutes);
router.use("/v1/api", tiposRoutes);
router.use("/v1/api", gastosRoutes);
router.use("/v1/api", presupuestosRoutes);
// router.use("/v1/api", tareaProductoRoutes);

export default router;
